DROP TABLE stock_log;
CREATE TABLE stock_log ( 
    id   INTEGER        PRIMARY KEY ASC AUTOINCREMENT,
    code VARCHAR( 10 ),
    今开   VARCHAR( 10 ),
    昨收   VARCHAR( 10 ),
    当前   VARCHAR( 10 ),
    最高   VARCHAR( 10 ),
    最低   VARCHAR( 10 ),
    竞买   VARCHAR( 20 ),
    竞卖   VARCHAR( 20 ),
    成交   VARCHAR( 20 ),
    成交额  VARCHAR( 20 ),
    买一量  VARCHAR( 20 ),
    买一价  VARCHAR( 10 ),
    买二量  VARCHAR( 20 ),
    买二价  VARCHAR( 10 ),
    买三量  VARCHAR( 20 ),
    买三价  VARCHAR( 10 ),
    买四量  VARCHAR( 20 ),
    买四价  VARCHAR( 10 ),
    买五量  VARCHAR( 20 ),
    买五价  VARCHAR( 10 ),
    卖一量  VARCHAR( 20 ),
    卖一价  VARCHAR( 10 ),
    卖二量  VARCHAR( 20 ),
    卖二价  VARCHAR( 10 ),
    卖三量  VARCHAR( 20 ),
    卖三价  VARCHAR( 10 ),
    卖四量  VARCHAR( 20 ),
    卖四价  VARCHAR( 10 ),
    卖五量  VARCHAR( 20 ),
    卖五价  VARCHAR( 10 ),
    日期   VARCHAR( 10 ),
    时间   VARCHAR( 10 ) 
);
